# Unity 기본 디렉토리
Library
library
Temp
temp
Obj
obj
Build
build
Builds
builds
UserSettings
usersettings
MemoryCaptures
memorycaptures
Logs
logs

# Asset Store 도구
**/Assets/AssetStoreTools
**/assets/assetstoretools

# Plastic SCM
/Assets/Plugins/PlasticSCM*
/assets/plugins/PlasticSCM*

# Unity 임시 파일
*.private
*.private.meta
^*.private.[0-9]+$
^*.private.[0-9]+.meta$
~UnityDirMonSyncFile~*

# IDE 디렉토리
.vs
.vscode
.idea
.gradle

# IDE 생성 파일
ExportedObj
.consulo
*.csproj
*.unityproj
*.sln
*.suo
*.tmp
*.user
*.userprefs
*.pidb
*.booproj
*.svd
*.pdb
*.mdb
*.opendb
*.VC.db
*.vsconfig
*.pidb.meta
*.pdb.meta
*.mdb.meta

# Unity 시스템 파일
sysinfo.txt
crashlytics-build.properties

# 빌드 파일
*.apk
*.aab
*.app
*.unitypackage

# Addressables
**/Assets/AddressableAssetsData/*/*.bin*
**/assets/addressableassetsdata/*/*.bin*
**/Assets/StreamingAssets/aa.meta
**/assets/streamingassets/*/aa/*

# 시스템 파일
.DS_Store*
Thumbs.db
Desktop.ini

# Git 관련
.git/
.gitignore
.gitattributes
*.iml
.idea/
.git

# 추가된 항목들
*.blend1
*.blend1.meta
/[Rr]ecordings/
*.DotSettings.user
mono_crash.*
*.unitypackage.meta
InitTestScene*.unity*
/ServerData
/[Aa]ssets/AddressableAssetsData/link.xml*
/[Aa]ssets/Addressables_Temp*
*.stacktrace
*.crash
*.xcworkspace
*.xcuserdata
*.pbxuser
*.mode1v3
*.mode2v3
*.ipa
*.xcodeproj
*.cmo3
*.psd
*.log
*.bak
*.meta~

# 대용량 미디어 파일
*.mp4
*.avi
*.mov
*.wmv
*.flv
*.mkv
*.webm
*.m4a
*.m4v
*.m4b
*.m4r
*.m4p

# 특정 플러그인
/Assets/Plugins/FiveMinuteChat
/Assets/Plugins/WebGLTemplates
